export const FETCH_AUTH = 'FETCH_AUTH';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_USER_UPDATE = 'FETCH_USER_UPDATE';
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_UPDATE_SUCCESS';
export const FETCH_USER_UPDATE_ERROR = 'FETCH_USER_UPDATE_ERROR';
export const FETCH_WHO_IS_THIS = 'FETCH_WHO_IS_THIS';
